# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lOSnBuTOo4ObiqhAZHGxiPxH_8TlBv_2
"""

! pip install streamlit

import streamlit as st

# Title of the app
st.title("Welcome to My Streamlit App!")

# Text input for user to enter their name
name = st.text_input("Ahmad:")

# Button to submit the name
if st.button("Submit"):
    if name:
        st.success(f"Hello, guys! Welcome to my app.")
    else:
        st.warning("Ahmad")